# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['lerev/__main__.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('lerev/plugin_source.py', 'lerev'),
        ('lerev/bridge.py', 'lerev'),
        ('lerev/config.py', 'lerev'),
        ('lerev/discovery.py', 'lerev'),
        ('lerev/__init__.py', 'lerev'),
        ('core', 'core'),
    ],
    hiddenimports=[
        'lerev',
        'lerev.bridge',
        'lerev.cli',
        'lerev.config',
        'lerev.discovery',
        'lerev.plugin_source',
        'core.routing.v26.memory_manager',
        'core.routing.v26.persistence',
        'core.routing.v26.security',
        'core.routing.v26.experience',
        'core.routing.v26.identity',
        'core.routing.v26.memory_types',
        'core.routing.v26.memory_store',
        'core.routing.v26.semantic_encoder',
        'core.routing.v26.similarity',
        'pydantic',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'scipy',
        'pandas',
        'PIL',
        'cv2',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='lerev',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
